services:
  - type: web
    name: ai-music-player
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        value: mongodb+srv://saurav982216_db_user:hGcStjbBugg2K5se@cluster0.lruurc9.mongodb.net/ai-music-player
      - key: CLOUDINARY_CLOUD_NAME
        value: dchyewou4
      - key: CLOUDINARY_API_KEY
        value: 378845981546511
      - key: CLOUDINARY_API_SECRET
        value: tIE3-JdRdzTDseFKji7It-fjBs0
    plan: free
    autoDeploy: true